### ISSUE TITLE
Prevent scrolling on the body while open

### ISSUE THREAD

**Issue by pkrawc** [Upmostly/modali#2]
The component should either set a no-scroll class on the body or should manually set the body's style with `document.body.overflowX = "hidden"`.

**Comment by jcrowson** [comment]
@pkrawc Agreed. Thoughts on a good approach?

**Comment by pkrawc** [comment]
Hey, sorry. I believe I was on Chrome for Android at the time.

**Comment by jcrowson** [comment]
@pkrawc Ok, I'll test it out and push a fix.
