### ISSUE TITLE
Content is shifting to left on mobile devices

### ISSUE THREAD

**Issue by jcrowson** [Upmostly/modali#20]
Content is shifting to the left by 15px (the width of a sidebar) on mobile devices.

**Comment by jcrowson** [comment]
Fixed and included in branch v1.2.

**Comment by mk0y** [comment]
This is happening even on Chrome desktop browsers for me: https://upmostly.github.io/modali/

**Comment by joshuaiz** [comment]
Same for me in Chrome desktop.
